const axios = require('axios');


var newAutoGeneratedId;

const messageFunctions = {

    addMessage: async () => {
        await axios.post("http://localhost:3001/messageCreation", {
            headers: {
                accept: "application/json",
                "Content-Type": "application/json",
            },
            data: {
                email: "email",
                title: "title",
                description: "description",
                time: "currentTime",
            }
        }).then((res) => {
            result = res.data.success;
            newAutoGeneratedId = res.data.newId
        }).catch(err => 'error');
        return result;
    },

    getMessage: async () => {
        await axios.get("http://localhost:3001/messages").then((response) => {
            if (Object.keys(response).length !== 0)
                result = true;
            else
                result = false;
        })
        return result;
    },

    deleteMessage: async () => {
        await axios.post("http://localhost:3001/messageDeletion", {
            headers: {
                accept: "application/json",
                "Content-Type": "application/json",
            },
            data: {
                id: newAutoGeneratedId,
            }
        }).then((res) => {
            result = res.data.success;
        }).catch(err => 'error');
        return result;
    },
}

module.exports = messageFunctions;